//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTalo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sauna
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sauna()
        {
            this.Talo = new HashSet<Talo>();
        }
    
        public int Id { get; set; }
        public string Koodi { get; set; }
        public string Tyyppi { get; set; }
        public string Tila { get; set; }
        public Nullable<int> Lampotila { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Talo> Talo { get; set; }
    }
}
